spring.application.name=AirtelInventorySystem
spring.datasource.url=jdbc:mysql://localhost:3306/airtel_db
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

server.port=8080

spring.thymeleaf.cache=true